version: '3.1'

services:
  kafka-manager:
    container_name: kafka-manager
    image: sheepkiller/kafka-manager
    restart: always
    ports:
      - 9000:9000
    environment:
      KM_VERSION: 1.3.3.17
      ZK_HOSTS: 192.168.1.6:2184,192.168.1.6:2182,192.168.1.6:2183