version: '3.1'

services:
  zk:
    image: zookeeper
    restart: always
    hostname: zk
    ports:
      - 2181:2181
    volumes:
      - "./zk/data:/data"
      - "./zk/datalog:/datalog"
      - "./zk/conf:/conf"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:2888