version: '3.1'

services:
  kafka:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka
    ports:
      - 9092:9092
    volumes:
      - "./kafka/docker.sock:/var/run/docker.sock"
      - "./kafka:/kafka"
    environment:
      KAFKA_VERSION: 1.1.0
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.116
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 192.168.0.116:2181